services:
  postgres:
    image: "postgres:15"
    container_name: "postgres-dev"
    environment:
      POSTGRES_DB: "bacao_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./docker_volume/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
