services:
  postgres:
    image: "postgres:15"
    container_name: "postgres-dev"
    environment:
      POSTGRES_DB: "bacao_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./docker_volume/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped


  redis:
    image: redis/redis-stack-server:6.2.6-v17
    platform: linux/arm64
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - ./docker_volume/redis:/var/lib/redis/data
    restart: always
