application:
  jwt:
    auth: Smartee-Auth-Service
    jwt_expiration: 86400000
    refresh_jwt_expiration: 2592000000

spring:
  application:
    name: bacao
  liquibase:
    enabled: false
  #    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/bacao_db}
    username: ${JDBC_DATABASE_USERNAME:admin}
    password: ${JDBC_DATABASE_PASSWORD:root}
  messages:
    basename: static/messages
    encoding: UTF-8
  socket:
    port: 9092
    host: localhost
  redis:
    lettuce:
      port: 6379
      host: localhost

server:
  port: 8082

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    tryItOutEnabled: true
    tagsSorter: alpha
    filter: true